apiVersion: tm.solution-soft.com/v1alpha1
kind: TimeMachine
metadata:
  name: timemachine-sample
spec:
  TM_LICHOST: "172.0.0.1"
  TM_LICPORT: "57777"
  TM_LICPASS: "docker"
  imagePullSecrets: []
  replicaCount: 1
  service:
    port: 7800
    targetPort: 7800
    type: NodePort  
